### ISSUE TITLE
WARNING! Bacrypt.com is a SCAM!

### ISSUE THREAD

**Issue by rompire** [monero-project/monero-site#1581] opened 2021-04-17 23:29 UTC
*I've created a [pull request](https://github.com/monero-project/monero-site/pull/1580) for this, so I'm pasting the issue description here:

We've tried to exchange 5000 USDC to 14.00667577 XMR which was equivalent to $5000 US plus fees.
Bacrypt has a timer set for every exchange you make, it's about half an hour.
The coins were were transferred to the Bacrypt's wallet about 15 minutes before the timer expiration.
Once the timer has expired, the money was never transferred to our wallet.

Here is the proof of the transaction: 0x0abc8daeccc0e57bc1fbd02ee04c59ae61c2521e3b97566447994e796822eedf
You can also view here: https://etherscan.io/tx/0x0abc8daeccc0e57bc1fbd02ee04c59ae61c2521e3b97566447994e796822eedf

Here is our conversation with the support team:
Q: "Can you confirm that you’ve received the funds?"
A: "This USDC address does not belong to our service."
Q: "It looks like one of your wallets: 0xbfe830e781d40a3aa796028f7c05666234280f2b (attached the screenshot)"
A: "As you can see in the screenshot, either the exchange is made on a phishing site, or the screenshot itself is false, because we have 20 digits in the exchange number. And in the screenshot there are 10 digits in the exchange number."

**Comment by Bacrypt** [comment] 2021-04-18 07:12
This is a blatant lie, you have not created an exchange with us and we have not received any payment from you!

**Comment by Bacrypt** [comment] 2021-04-18 07:19
Here is direct evidence that you are lying!
1. The timer on our site is not 30 minutes, but 15 minutes.
2. In the screenshot that you are trying to provide as proof, you can see that in the exchange number you have 10 digits, on our website in the exchange number used 20 digits.
3. You do not provide any evidence other than a screenshot, which is a fake.
4. The USDC address you provide in the transaction does not belong to us.

**Comment by Bacrypt** [comment] 2021-04-18 07:21
On the above grounds please close the issues rompire, as rompire has never been our customer and never created an exchange with us, this is completely fake accusations without any evidence.

**Comment by Bacrypt** [comment] 2021-04-18 07:30
We see that you put without any explanations and proving our guilt to remove our site from your site. This is completely wrong, as these are completely fake accusations. 
And so from your site will soon remove all the Exchange, and all the anonymity of Monera without Exchange comes to naught as if the client will not know where to exchange Monera anonymously, and Monera anonymity remains very little think for it maybe someone wants that Monera would be possible to exchange only on exchanges with the passage of KYC / AML.

**Comment by Bacrypt** [comment] 2021-04-18 08:04
Team Monera, think about what you need before you remove the claim site at least in some way, not just delete the site at the first false claim you will not remain an exchanger in the list and Monera will lose much of its anonymity, as all exchangers make the exchange anonymous, and without exchangers customers will only exchange Monera with AML / KYC. We understand in the near future there will be a lot of such fake claims and you will remove all exchangers from your site and Monera will lose its anonymity almost completely.

Translated with www.DeepL.com/Translator (free version)

**Comment by Bacrypt** [comment] 2021-04-18 12:58
Also want to draw the attention of the Monero team that this fake accusation is also confirmed by the fact that the transaction https://etherscan.io/tx/0x0abc8daeccc0e57bc1fbd02ee04c59ae61c2521e3b97566447994e796822eedf which the user indicates most likely was made on his own purse as well 
since USDC from this purse were not transferred further, and so remained on this purse.
https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48?a=0xbfe830e781d40a3aa796028f7c05666234280f2b

**Comment by Bacrypt** [comment] 2021-04-18 13:04
Team Monera, if you pay attention to all the facts that we have provided, you will realize that this accusation against us is bogus and without any evidence to support it. 
Team Monera we are ready to answer any questions you may have and provide any evidence you may request to prove that this user is a fake.

**Comment by Bacrypt** [comment] 2021-04-18 13:06
And also note that this is an anonymous user who was registered yesterday and immediately wrote fake accusations.

**Comment by rompire** [comment] 2021-04-20 02:39
The screenshot is 100% Real:
<img width="1166" alt="Screen Shot 2021-04-16 at 11 22 32 PM" src="https://user-images.githubusercontent.com/54870362/115329168-e58b2a80-a15f-11eb-9aa3-d974503770d1.png">

**Comment by rompire** [comment] 2021-04-20 02:41
Keep in mind, that there is no incentive for us to lie, and there is a $5000 incentive for @Bacrypt to lie.

**Comment by rompire** [comment] 2021-04-20 02:49
@Bacrypt here is the exchange order: https://bacrypt.com/en/exchange-order/66068207122205330646

**Comment by rompire** [comment] 2021-04-20 03:09
@Bacrypt also try this one: https://bacrypt.com/en/order/6485234734 it looks like an Order ID(10 digits) not an Exchange ID (20 digits)

**Comment by Bacrypt** [comment] 2021-04-20 06:03
You're lying and what your incentive is, we don't know.
Anyone can be convinced of this by creating an exchange on our site, and it will immediately become clear that your screenshot is a fake

**Comment by Bacrypt** [comment] 2021-04-20 06:18
In your screenshot it says Exchange # 6485234734
And now you write a link in which you write a completely different exchange number 
66068207122205330646 which you just made up yourself.

https://bacrypt.com/en/order/6485234734 This link has nothing to do with our service as in the link /order/ and should be /exchange-order/ and in the link exchange number with 10 digits and should be 20 digits.

We are 100% sure that you just transferred from 1 of your wallets to 2 of your wallets to create a transaction in blockchain and it is clearly visible because the USDC is not mixed up further.
https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48?a=0xbfe830e781d40a3aa796028f7c05666234280f2b

**Comment by Bacrypt** [comment] 2021-04-20 06:24
And in the screenshot you have written time to pay 20:19 Minutes - this is not possible, because the payment is given only 15 minutes!

**Comment by Bacrypt** [comment] 2021-04-20 06:25
And that is another fact that you are lying.

**Comment by Bacrypt** [comment] 2021-04-20 06:28
Any user can make sure that the screenshot is a fake, just make an exchange on our site and see the differences that we described.

**Comment by rompire** [comment] 2021-04-20 07:02
@Bacrypt as you previously mentioned that `since USDC from this purse were not transferred further, and so remained on this purse.` this means one of two things:

**1.** Either you're lying and keeping the money for yourself, which makes you a thief. And since you're not going to transfer back what you owe, **I'd recommend you donating the entire amount to a charity of your choice instead. This will help you in a long run, trust me.**

**2.** If you really think that you don't have access to that wallet: **0xbfe830e781d40a3aa796028f7c05666234280f2b** (_since the money wasn't moved from that wallet yet..._) this potentially means that there was an error on your website, which makes me think, how reliable your service is... So, in this case double check the **Order ID**: 6485234734  and all associated USDC addresses along with it. Maybe search the entire database for that address: "0xbfe830e781d40a3aa796028f7c05666234280f2b". Set some db query flags such as `cancelled=1`.

**Comment by Bacrypt** [comment] 2021-04-20 07:06
You're the only one lying here!
This exchange number 6485234734 does not exist, the exchange number must be 20 digits.

**Comment by rompire** [comment] 2021-04-20 07:21
@Bacrypt I assure you we're telling the truth. Try this `57549918388820386579` exchange number as well.

**Comment by rompire** [comment] 2021-04-20 08:37
@Bacrypt we've made some tests prior to sending the final transaction. Here is the list of the browser's history in relation to [the transaction](https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48?a=0xbfe830e781d40a3aa796028f7c05666234280f2b):
<img width="567" alt="Screen Shot 2021-04-20 at 4 32 21 AM" src="https://user-images.githubusercontent.com/54870362/115364469-6c0c3000-a191-11eb-9330-c0357352b300.png">
Test them all, and see if you can find the correct one:
`11567027458919205746`
`59409025997664012983`
`66068207122205330646`
`57549918388820386579`

**Comment by Bacrypt** [comment] 2021-04-20 17:51
Date of creation 20.04.2021 Exchange No.: 57549918388820386579
The exchange amount is 500 USDC you did not pay it.
This exchange was created today and the transaction you write was sent 3 days ago.
What does an exchange that was created today have to do with a transaction that was sent 3 days ago?

**Comment by Bacrypt** [comment] 2021-04-20 17:56
Date of creation 20.04.2021 Exchange No.:11567027458919205746
Date of creation 20.04.2021 Exchange No.:59409025997664012983
Date of creation 20.04.2021 Exchange No.:66068207122205330646
Date of creation 20.04.2021 Exchange No.:57549918388820386579
You created these exchanges today and did not make payment on any of them.
Your screenshot of the browser history shows that you have created these 4 exchanges, well, what do they have to do with the amount of 5000 USDC that you specify? If the transaction was sent 3 days ago and the exchanges were created today.

**Comment by Bacrypt** [comment] 2021-04-20 18:08
That's what we wrote that your accusations are completely fake, and we've already proven that repeatedly.

When you were creating test exchanges today, did you see the difference with your screenshot? that the timer and exchange number all look completely different from what you have in the screenshot that sent you a partner.

So deal with your partner 
We did not have an exchange with this number, which is on the screenshot, and such a number can not be.
And the screenshot is a fake.

**Comment by Bacrypt** [comment] 2021-04-20 18:15
If the Monera team needs any additional evidence, we are willing to provide anything you request.

**Comment by rompire** [comment] 2021-04-20 21:02
The original exchange went through as an ‘/en/order/...’ url **NOT** as an ‘/en/exchange-order/...’, it’s your website look it up! I can’t look at the source code of your site to look into the what the ‘/en/order/..’ does. Yes, the time was 15 minutes last time we tested. Yes, the ‘exchange-order’ has 20 digits not 10. The the original URL that was in the browser history is the following:
https://bacrypt.com/en/order/6485234734

Did you change your website on the 16th?

We do not have access to the following wallet: 0xbfe830e781d40a3aa796028f7c05666234280f2b

If you don’t have access to it either, the money is lost! **We’d rather donate this amount than spend it on this nonsense!**

**Comment by Bacrypt** [comment] 2021-04-20 21:23
We never had /en/order/... , 10 digits in the exchange number, and a timer of 30 minutes!

**Comment by Bacrypt** [comment] 2021-04-20 21:29
Let's do the following so that you do not draw your own screenshots and the like.
Make a video of your pc screen from your phone as you open your browser and go to the stories and there you see the link https://bacrypt.com/en/order/6485234734
Only the video should show that your browser is closed and you open it again and go to the history and show the link. 
Do it then we can continue the dialogue since we have already proved that your screenshot is a fake.

**Comment by rompire** [comment] 2021-04-20 23:39
@Bacrypt you got it! We’ll keep you posted.

**Comment by rompire** [comment] 2021-04-21 01:12
@Bacrypt Here is the proof: https://www.youtube.com/watch?v=F6IlMRhznqI

**Comment by rompire** [comment] 2021-04-22 00:18
<img width="766" alt="bacryptdotcom" src="https://user-images.githubusercontent.com/54870362/115637540-607a4f80-a2de-11eb-893e-46d42514a23a.png">
*The review above was not ours.


Source: https://www.trustpilot.com/review/bacrypt.com?languages=all

**Comment by rompire** [comment] 2021-04-22 00:24
@Bacrypt https://hebertpark.com/bacrypt-com

**Comment by selsta** [comment] 2021-04-22 00:40
@Bacrypt The user seems to have provided the requested proof.

**Comment by fluffypony** [comment] 2021-04-22 15:33
<img width="528" alt="Screen Shot 2021-04-22 at 11 33 19 AM" src="https://user-images.githubusercontent.com/1944293/115742308-8ba48380-a35e-11eb-8089-676273aad198.png">

That's an exit scam if I ever saw one.

**Comment by rompire** [comment] 2021-04-22 17:21
> <img alt="Screen Shot 2021-04-22 at 11 33 19 AM" width="528" src="https://user-images.githubusercontent.com/1944293/115742308-8ba48380-a35e-11eb-8089-676273aad198.png">
> 
> That's an exit scam if I ever saw one.

@fluffypony and this guy was going places: `We understand in the near future there will be a lot of such fake claims and you will remove all exchangers from your site and Monera will lose its anonymity almost completely.`

**Comment by SupportBacrypt** [comment] 2021-04-22 19:52
Sorry for the long response, it is due to the fact that our service was made large DDOS attack, currently undergoing technical work, the service will be restored within 2-3 days.

**Comment by SupportBacrypt** [comment] 2021-04-22 19:56
@Rompire you crossed a red line with a DDOS attack! We will have to contact law enforcement, don't think you hid yourself with a VPN

**Comment by SupportBacrypt** [comment] 2021-04-22 20:03
https://www.youtube.com/watch?v=F6IlMRhznqI
As for your video, if anyone looks carefully at your video will understand that this is the same fake video as your screenshot.
00:45 seconds of the video you show, supposedly on the exchange page, well you forgot to fabricate. 
Before the exchange page, there should be the main page of the site from which you need to create the exchange!
And according to your history, you allegedly went from the site monero immediately to the page exchange, well, it is not possible because that would go to the page exchange must first create an exchange, and this is done in any service, not only us.

By doing so, we have provided irrefutable proof that your screenshot and your video are fake.

**Comment by SupportBacrypt** [comment] 2021-04-22 20:07
https://www.trustpilot.com/review/bacrypt.com?languages=all
It was left at the same time that you made a complaint here!
Feedback which also does not provide any evidence only fake accusations this review will be removed soon!

**Comment by rompire** [comment] 2021-04-22 20:08
@SupportBacrypt this was **not a DDOS attack.**

This was a PrivacyProtect.org complaint:

<img width="688" alt="PrivacyProtect" src="https://user-images.githubusercontent.com/54870362/115778611-ef41a780-a384-11eb-895a-9c0b9c18eb6f.png">

**Comment by luigi1111** [comment] 2021-04-22 20:11
Ok this is getting to be quite something.

**Comment by SupportBacrypt** [comment] 2021-04-22 20:12
+ DDOS attack

**Comment by SupportBacrypt** [comment] 2021-04-22 20:13
@rompire I hope you will be punished to the fullest extent of the law for your actions!

**Comment by rompire** [comment] 2021-04-22 20:15
@SupportBacrypt you can hope all you want. What we want is our money back.

**Comment by SupportBacrypt** [comment] 2021-04-22 20:18
We believe that you are working at the behest of our competitors, for whom we are a nuisance.
Nothing terrible 2-3 days and the service will be restored.
Most importantly, it is now clear to everyone that you are not a user, but an intruder!

**Comment by SupportBacrypt** [comment] 2021-04-22 20:20
What your money we gave you a lot of facts that your screenshot is a fake, now also brought the indisputable facts that your video is a fake.
You don't have to waste any more time, everyone knows you're a fake!

**Comment by rompire** [comment] 2021-04-22 20:23
@SupportBacrypt well, what can we say? Good luck to your next customers!

**Comment by SupportBacrypt** [comment] 2021-04-22 20:25
Good luck to you too hope you will be punished to the fullest extent of the law!

**Comment by SupportBacrypt** [comment] 2021-04-22 20:31
Team Monero I think this issue can be closed since it became clear to all who is rompire, fake and dedoser.

Thank you all for your patience in dealing with this bogus accusation, and in the future I think it's clear to everyone now that you shouldn't trust bogus accusations to the first person you meet. They need to be examined in detail and demand proof of the accusation.

**Comment by rompire** [comment] 2021-04-22 20:31
@SupportBacrypt we are getting our layers involved in this case

The legal process will go through the domain registrar PublicDomainRegistry.com as well as the original party involved PrivacyProtect.org

Here is the public domain info: https://www.domain.com/whois/whois/?search=bacrypt.com

<img width="476" alt="bacrypt" src="https://user-images.githubusercontent.com/54870362/115780999-d686c100-a387-11eb-95db-684d8c0bb241.png">

**Comment by rompire** [comment] 2021-04-22 20:33
@SupportBacrypt We're not yet sure what jurisdiction we have in Russia, but we'll keep you posted.

**Comment by SupportBacrypt** [comment] 2021-04-22 20:35
As for the video for some reason you have not answered how you were so wrong when you made a fake video? Probably in a hurry and did not think originally yes?

**Comment by SupportBacrypt** [comment] 2021-04-22 20:37
So why can't you give an answer? To the indisputable facts that your video is a fake.

**Comment by rompire** [comment] 2021-04-22 20:39
@SupportBacrypt as for the video, we've removed several unrelated urls for that day prior to filming it for privacy reasons. The rest of it is 100% real.

**Comment by SupportBacrypt** [comment] 2021-04-22 20:45
Yes, deleted the most important thing:)
Your thoughts:
Choosing what to delete and thinking let's delete the exchange creation process:) but I'll leave everything else.

**Comment by SupportBacrypt** [comment] 2021-04-22 20:47
At the moment the thoughts are in your head:
The customer will not pay for the work I did not do fully what else to spoil them, oh I will lay out whois data let everyone see what a genius I am.

**Comment by SupportBacrypt** [comment] 2021-04-22 20:48
I'll tell you a secret, the data whois can see anyone they are in the public domain:)

Goodbye friend I hope you will be punished.

**Comment by rompire** [comment] 2021-04-22 20:50
@SupportBacrypt hope all you want, **but we want our money back!**

**Comment by rompire** [comment] 2021-04-22 21:12
> I'll tell you a secret, the data whois can see anyone they are in the public domain:)

Not when you're protected by [PrivacyProtect.org](https://privacyprotect.org/).

**Comment by rompire** [comment] 2021-04-22 22:41
@SupportBacrypt no more games Yuriy Rodivilov from Bryansk Russia. You have 24 hours to return the money or we’re going to higher authorities.

![AE357C31-5BD1-494E-BC96-466F8D021C38](https://user-images.githubusercontent.com/54870362/115793490-32f2dc00-a39a-11eb-94fa-84694eadbe95.jpeg)

**Comment by erciccione** [comment] 2021-04-24 07:42
Removed with #1580. Closing this as it's resolved. Please don't publish personal informations.

**Closed by erciccione** 2021-04-24 07:42 UTC

**Comment by fluffypony** [comment] 2021-04-24 13:28
Locking this, doxxing on GitHub is beyond the pale.
