### ISSUE TITLE
Revise "what is monero" page

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-site#1484] opened 2021-02-27 01:11 UTC
The current "What is Monero" should go further in explaining the most important qualities that set Monero apart from other assets.

***Note: the proposed revision should be mostly judged for content, not for style. It needs a further redesign. I'm not good at that part.***

Notice that the proposed version very clearly focuses on Monero's advantages in a way that immediately convey that Monero is not a shitcoin. It also contains calls for actions at the bottom:

"Join Community": https://www.getmonero.org/community/hangouts/
"Get Monero": https://www.getmonero.org/community/merchants/#exchanges
"Show me the full details": https://www.getmonero.org/resources/about/

### Current

![image](https://user-images.githubusercontent.com/12520755/109370444-eee5ce00-7865-11eb-987f-fc15ed854816.png)

### Proposed

![image](https://user-images.githubusercontent.com/12520755/109370432-e097b200-7865-11eb-8a15-1c46b9bfc4e9.png)

We can leave the video card at the bottom. I'm indifferent about that.

Conflicts with #1480. Related to #1483 #1485 #1486

**Comment by robby-dermody** [comment] 2021-02-27 03:38
as a possible alternative, this page could also be linked from the homepage only (e.g. the "Learn why it's the standard"), and keep the current What is Monero page (possibly with certain revisions that can be addressed separately)?

**Comment by erciccione** [comment] 2021-02-27 08:19
The suggestions you are proposing are basically entire redesigns and some would require long discussions before being implemented. I agree with some of the changes, but implementing them would take a lot of time and resources

Beside, some of these pages were refreshed not long ago and the text changed. I wouldn't make another (more intrusive) redesign any time soon.

**Comment by erciccione** [comment] 2021-02-27 08:56
On the merit of this issue, i like the idea of adding engagement buttons, but beside the fact that the text of the page is being changed by #1481 (so shouldn't be changed again any time soon), i don't like the content of those bullet points. They don't really explain what Monero is (which is the point of the page) and some of the content seems to be redundant with the 'About' page (points 3 and 4).

**Comment by tallest-man** [comment] 2021-03-01 17:12
@erciccione would you be able to provide some additional comments on your reasoning for:
"Beside, some of these pages were refreshed not long ago and the text changed. I wouldn't make another (more intrusive) redesign any time soon." and "(so shouldn't be changed again any time soon)"?

Is this due to resource constraints or some other reason? Asking because I believe that the frequency of re-design shouldn't be the sole factor that prevents a re-design from occurring, if that re-design is going to serve the needs of the project in a way that provides more benefit than it costs.

**Comment by erciccione** [comment] 2021-03-01 17:52
> I believe that the frequency of re-design shouldn't be the sole factor that prevents a re-design from occurring

@tallest-man it's not. I'm ok with aimed redesigns if there are useful improvements suggested and it's not just a "i like this text better" kind of situation. Beside that, two important additional factors should be considered:

- The new strings will need to be translated again. The text of some pages were changed not long ago. Nobody suggested improvements at the time, so the changes went in as they were. Then, translators started to work on these new strings. Some of these translators were also funded through CCS proposals. Changing strings means translators' work will be wasted. Now think that (almost) every page on this website is available in 13 languages and how many people you need to translate everything (even if for most people translations simply happen, there is a huge amount of work and coordination in the background between me and the translators. Without even considering the work necessary on Weblate itself).
- The proposed changes will need to be implemented by somebody. I'm ok with applying the changes if people want them, but that would take out time from other important works that are still in progress (like converting the entire user guides and moneropedia to translate them on Weblate). Even if somebody else would take care of making the changes, reviewing them will still take considerable time.

To reiterate: I'm ok with making substantial changes, but only when really necessary. Also, the amount of resources to invest (for translators, reviewers and committers) should be considered.

In this case, personally i'm ok with adding the buttons or changing the header, even if i don't consider that a priority or something particularly useful, but i don't like the new content (as explained in my comment above) that is being proposed and i don't think it worth spending so much time and resources for it.

**Comment by erciccione** [comment] 2021-03-04 09:09
This is actually a duplicate of #1480. Please continue the discussion there.

**Closed by erciccione** 2021-03-04 09:09 UTC
Labels: duplicate, enhancement
