### ISSUE TITLE
Remove changehero.io from the list of merchants

### ISSUE THREAD

**Issue by Scam-ChangeHero** [monero-project/monero-site#1695] opened 2021-07-02 19:23 UTC
This exchanger is engaged in an exceptional scam when the large amount exchanger dumps users.
They cheated me out of 15,000 USD 
When exchanging for smaller amounts changed without problems and everything quickly as soon as I exchanged the amount of 15000 USD, They wrote to me that they do not have such a request number and the wallet does not belong to their service.
Scammers!!!

**Comment by erciccione** [comment] 2021-07-03 06:58
Duplicate of #1660

**Closed by erciccione** 2021-07-03 06:58 UTC
Labels: 🏪 merchant: removal, 🔍 Needs investigation
