### ISSUE TITLE
feed: invalid links

### ISSUE THREAD

**Issue by leonklingele** [monero-project/monero-site#1201] opened 2020-09-18 20:47 UTC
Every link in the [feed](https://www.getmonero.org/feed.xml) is prefixed with `https://www.getmonero.org/`, resulting in invalid URLs. Example:

```atom
<link href="https://www.getmonero.org/https://www.getmonero.org/feed.xml" rel="self" type="application/atom+xml"/>

[..]

<content type="html" xml:base="https://www.getmonero.org/https://www.getmonero.org/2020/09/17/monero-0.17-released.html">
```

**Comment by erciccione** [comment] 2020-09-19 13:46
This is a duplicate of #1162. The problem is fixed with #1164, which will be merged soon.

**Closed by erciccione** 2020-09-19 13:46 UTC
Labels: duplicate
