### ISSUE TITLE
Listing on the Merchants&Exchanges page

### ISSUE THREAD

**Issue by SZ-olya** [monero-project/monero-site#1926] opened 2022-02-09 09:21 UTC
Hey, I'm Olya, a marketing manager from [swapzone.io](https://swapzone.io/) aggregator of crypto exchanges. We've been supporting XMR non-custodial swaps since the inception of our service and we'd be grateful if you placed our link under the Swappers section on the Merchants&Exchanges page. 
ps Swapzone - this is the right spelling. NOT SwapZone.

**Comment by HardenedSteel** [comment] 2022-09-13 16:21
duplicate of #1970, issue can be closed @erciccione

**Closed** 2022-10-20 08:33 UTC
Labels: 🏪 merchant
